name: Create Azure Infrastructure and Deploy Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Login to Azure CLI'
        uses: azure/login@v2
        with:
          client-id: e9fa3de9-bc08-4d19-8c0f-a8f07b94b116
          tenant-id: c24bfd69-d415-4070-9b5d-763af27aa9e0
          subscription-id: 521a887f-4f1d-4e0b-a5fb-9ae11e75525c

      - name: 'Login to Azure Container Registry'
        run: az acr login --name cosmicappacr

      - name: 'Build and push app service Docker image'
        run: |
          docker build . -f app/Dockerfile -t cosmicappacr.azurecr.io/astro-app-service:${{ github.sha }}
          docker push cosmicappacr.azurecr.io/astro-app-service:${{ github.sha }}

      - name: 'Build and push astrology service Docker image'
        run: |
          docker build . -f astrology-service/Dockerfile -t cosmicappacr.azurecr.io/astro-astrology-service:${{ github.sha }}
          docker push cosmicappacr.azurecr.io/astro-astrology-service:${{ github.sha }}

      - name: 'Deploy app service Container App'
        run: |
          az containerapp update \
            --name cosmicapp-app \
            --resource-group cosmicapp-rg \
            --container-name cosmicapp-app \
            --image cosmicappacr.azurecr.io/astro-app-service:${{ github.sha }} \
            --target-port 8000

  deploy-function-app:
    needs: build-and-deploy
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Login to Azure CLI'
        uses: azure/login@v2
        with:
          client-id: e9fa3de9-bc08-4d19-8c0f-a8f07b94b116
          tenant-id: c24bfd69-d415-4070-9b5d-763af27aa9e0
          subscription-id: 521a887f-4f1d-4e0b-a5fb-9ae11e75525c
          
      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 'Install Azure Functions Core Tools'
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
          
      - name: 'Deploy to Azure Function App'
        run: |
          cd daily-content-generator
          func azure functionapp publish cosmicapp-daily-content --force