name: Deploy Daily Content Generator to Azure Function App

on:
  push:
    branches:
      - main
    paths:
      - 'daily-content-generator/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Login to Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Set up Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 'Install Azure Functions Core Tools'
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
          
      - name: 'Deploy to Azure Function App'
        run: |
          cd daily-content-generator
          func azure functionapp publish cosmicapp-daily-content --force