name: Build, Push, and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
   
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log Code Checkout
        run: echo "Code checkout completed successfully."

      - name: 'Login to Azure CLI'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Log Azure CLI Login
        run: echo "Azure CLI login completed successfully."

      - name: 'Login to Azure Container Registry'
        run: az acr login --name cosmotalksacr
      - name: Log ACR Login
        run: echo "Azure Container Registry login completed successfully."

      - name: 'Build and push app service Docker image'
        run: |
          docker build . -f app/Dockerfile -t cosmotalksacr.azurecr.io/astro-app-service:${{ github.sha }}
          docker push cosmotalksacr.azurecr.io/astro-app-service:${{ github.sha }}
      
      - name: 'Build and push astrology service Docker image'
        run: |
          docker build . -f astrology-service/Dockerfile -t cosmotalksacr.azurecr.io/astro-astrology-service:${{ github.sha }}
          docker push cosmotalksacr.azurecr.io/astro-astrology-service:${{ github.sha }}

      - name: 'Deploy to Azure Container Apps'
        uses: azure/container-apps-deploy-action@v1
        with:
          resource-group: cosmotalks-rg
          containerAppName: cosmotalks-app
          imageToDeploy: cosmotalksacr.azurecr.io/astro-app-service:${{ github.sha }}

      - name: 'Deploy astrology-service to Azure Container Apps'
        uses: azure/container-apps-deploy-action@v1
        with:
          resource-group: cosmotalks-rg
          containerAppName: cosmotalks-astrology-service
          imageToDeploy: cosmotalksacr.azurecr.io/astro-astrology-service:${{ github.sha }}