name: Deploy Python Backend to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 'Login to Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Login to Azure Container Registry'
        run: az acr login --name cosmotalksacr

      - name: 'Build and push Docker image'
        run: |
          docker build . -f app/Dockerfile -t cosmotalksacr.azurecr.io/astro-backend:${{ github.sha }}
          docker push cosmotalksacr.azurecr.io/astro-backend:${{ github.sha }}

      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'cosmotalks-backend-app-unique'
          images: 'cosmotalksacr.azurecr.io/astro-backend:${{ github.sha }}'
          app-settings: 'WEBSITES_PORT=8000'